### ISSUE TITLE
Admin UI: check if username is email

### ISSUE THREAD

**Issue by rla** [rla/blog-core#59]
It is not currently checked under login and user edit forms.

**Comment by Anniepoo** [comment]
on my machine (release 0.0.3) it prefills the login with 'admin'  I have to manually change to admin@example.com

**Comment by rla** [comment]
What the browser prefills it with is not under our control.
Once #81 gets implemented, the issue should be less severe.
There is also #80 about #78 to finally fix broken inputs.

**Comment by rla** [comment]
Email address validation is also under user form, just checked.
