### ISSUE TITLE
adding block doesn't select all of default text

### ISSUE THREAD

**Issue by Anniepoo** [rla/blog-core#79]
1. start blog-core based system
2. go to blocks and click add
3. you will see form for new block
OBSERVED: first item (title) is not in focus
EXPECTED: first item would be in focus and all text selected

**Comment by rla** [comment]
I checked that this behavior does not depend on the entry type. So pages and posts have the same issue.

Focused field should probably depend on whether a new or an existing entry is opened.

 * For new entries, the title field should be in focus?
 * For existing entries, the content field should be in focus?

Selecting all text - not seen this behavior a lot. Could be used for a new entry and the title field but I would not add it for opening an existing entry and the content field.

**Comment by Anniepoo** [comment]
New entry defaults to 'Untitled' - user will presumably want to change that. 
fwiw I'd characterise this as a bug, not an enhancement - it's a UI glitch - on page load I have to do something to start entering my new entry - have to click in Title entry and then drag to select the existing 'Untitled' text.  I'm on Version 39.0.2171.95 m Chrome

**Comment by rla** [comment]
Tested with setting focus to content when existing entry is edited - does not feel good. For new entry and title field it works tho.

**Comment by Anniepoo** [comment]
wonder if it's a browser version issue.  It doesn't feel like a UI choice for me, it feels like a bug.

**Comment by rla** [comment]
It's not pushed yet. I'm refactoring whole admin ui code into KO components.

**Comment by rla** [comment]
This is same issue occurs when adding an user.

**Comment by rla** [comment]
Should be implemented in master now. Reopen if still an issue.
